version: "3.5"
services: 
    rabbit:
        image: rabbitmq:latest
        networks:
            - greenhouse
    postgres:
        image: postgres:latest
        networks:
            - greenhouse
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        env_file:
            - .env
    temperature_server:
        build: .
        networks:
            - greenhouse
        volumes: 
            - .:/code
        depends_on:
            - rabbit
        command: "./start.sh"

networks:
  greenhouse:
    name: greenhouse
