version: "2"
services: 
    rabbit:
        image: rabbitmq:latest
    temperature_server:
        build: .
        volumes: 
            - .:/code
        environment:
            - FLASK_APP=api.py
            - FLASK_DEBUG=1
        command: 'flask run -p 8000 -h 0.0.0.0'
        ports:
          - "8000:8000"
        depends_on:
            - rabbit

