version: "3.5"
services: 
    rabbit:
        image: rabbitmq:latest
        networks:
          - greenhouse
    temperature_server:
        build: .
        networks:
          - greenhouse
        volumes: 
            - .:/code
        depends_on:
            - rabbit
        command: "./start.sh"

networks:
  greenhouse:
    name: greenhouse
